### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by mrinalmanu** [mrinalmanu/class_assignments#3]

**Comment by YakutovDmitriy** [comment]
* `popcount` - ok
* `powers` - your solutions doesn't work on sample tests
* `subpalindrome` - why is it generator?
* `isIPv4`. Why are you printing result? Fix it
* `pascals`. You have arguments `n` and `r`, why? Fix it
* `fibonacci` - good try, but:
  1) You used several lines of code
  2) You return list of numbers, not one number

**Comment by mrinalmanu** [comment]
Hello dear Dimitry,

I've fixed the code.

I could not understand brackets2(). I tried to make another program brackets22() with a different logic but it doesn't work either.

**Comment by YakutovDmitriy** [comment]
* `valuesunion`, `subpalindrome`, `fibonacci` and `spiral` are ok
* `powers`. You do something strange here. What is `return dict.append(...)`?
* `isIPv4`. You returns nothing from the function

**Comment by mrinalmanu** [comment]
I fixed isIPv4(), I forgot to add return. In powers, I confused between the append option of list in dictionary. I've fixed both of them. Thank you.

**Comment by YakutovDmitriy** [comment]
* `powers` - It still doesn't work. Did you test it using sample tests?
* `isIPv4` -- there is no changes since my last checking in this function

**Comment by mrinalmanu** [comment]
I committed the changes.

**Comment by YakutovDmitriy** [comment]
* `powers` and `isIPv4` are ok
